Dontdrinkandroot\UtilsBundle\Entity\AutoIntegerIdEntity:
    type: mappedSuperclass
    id:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
