Dontdrinkandroot\UtilsBundle\Entity\UuidEntity:
    type: mappedSuperclass
    indexes:
        uuidIdx:
            columns:
                - uuid
    fields:
        uuid:
            type: guid
            nullable: false
            unique: true