parameters:
    ddr_utils.listener.doctrine.uuid.strategy: 'random'

services:

    ddr_utils.twig.bootstrap.pagination_extension:
        class: Dontdrinkandroot\UtilsBundle\Twig\BootstrapPaginationExtension
        arguments: ["@router"]
        tags:
            - { name: twig.extension }

    ddr_utils.form.type.flexdate:
        class: Dontdrinkandroot\UtilsBundle\Form\FlexDateFormType
        tags:
            - { name: form.type, alias: flexdate}

    ddr_utils.listener.doctrine.uuid:
        class: Dontdrinkandroot\UtilsBundle\Listener\Doctrine\UuidEntityListener
        calls:
            - ['setStrategy', [%ddr_utils.listener.doctrine.uuid.strategy%]]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    ddr_utils.listener.doctrine.created:
        class: Dontdrinkandroot\UtilsBundle\Listener\Doctrine\CreatedEntityListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    ddr_utils.listener.doctrine.updated:
        class: Dontdrinkandroot\UtilsBundle\Listener\Doctrine\UpdatedEntityListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    ddr_utils.routing.entity_loader:
        class: Dontdrinkandroot\UtilsBundle\Routing\EntityLoader
        arguments:
            - '@kernel'
        tags:
            - { name: routing.loader }
