services:
    ddr_utils.twig.bootstrap.pagination_extension:
        class: Dontdrinkandroot\UtilsBundle\Twig\BootstrapPaginationExtension
        arguments: ["@router"]
        tags:
            - { name: twig.extension }
